# Generated by Django 5.0.14 on 2026-04-07 12:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_candidate_company(apps, schema_editor):
    Candidate = apps.get_model("candidates", "Candidate")
    for candidate in Candidate.objects.select_related("owner").all():
        owner_company_id = getattr(candidate.owner, "company_id", None)
        if owner_company_id and candidate.company_id is None:
            candidate.company_id = owner_company_id
            candidate.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_comment_user_can_rate_user_can_shortlist_and_more'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.company'),
        ),
        migrations.RunPython(backfill_candidate_company, migrations.RunPython.noop),
    ]
