# Generated by Django 5.0.14 on 2026-04-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_user_company_owner'),
        ('candidates', '0002_candidate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('company', 'phone')},
        ),
    ]
