# Generated by Django 5.0.14 on 2026-04-07 12:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_company_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Company = apps.get_model("accounts", "Company")

    User.objects.filter(role="company").update(role="company_owner", is_owner=True)

    for company in Company.objects.select_related("user").all():
        owner = company.user
        if owner.company_id is None:
            owner.company_id = company.id
            owner.save(update_fields=["company"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_shortlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company_owner', 'Company Owner'), ('team_member', 'Team Member'), ('candidate', 'Candidate')], default='candidate', max_length=20),
        ),
        migrations.RunPython(migrate_company_roles, migrations.RunPython.noop),
    ]
