# Generated by Django 5.0.14 on 2026-04-09 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_company_user_to_owner(apps, schema_editor):
    Company = apps.get_model("accounts", "Company")
    for company in Company.objects.exclude(user_id=None):
        company.owner_id = company.user_id
        company.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_comment_user_can_rate_user_can_shortlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_company_user_to_owner, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
