# Generated by Django 5.0.14 on 2026-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_user_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_shortlist',
        ),
        migrations.AddField(
            model_name='user',
            name='team_role',
            field=models.CharField(blank=True, choices=[('editor', 'Editor'), ('reviewer', 'Reviewer'), ('approver', 'Approver')], max_length=20, null=True),
        ),
    ]
