# Generated by Django 5.0.14 on 2026-04-17 09:17 (manually edited to populate slugs first)

from django.db import migrations, models
from django.utils.text import slugify


def populate_company_slugs(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    for company in Company.objects.all():
        base = slugify(company.company_name) or f'company-{company.pk}'
        slug = base
        counter = 1
        while Company.objects.filter(slug=slug).exclude(pk=company.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        company.slug = slug
        company.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_deleted_at_company_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        # Step 1: add slug WITHOUT unique so existing rows can be ''
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, default=''),
            preserve_default=False,
        ),
        # Step 2: fill unique slug for every existing company row
        migrations.RunPython(populate_company_slugs, migrations.RunPython.noop),
        # Step 3: now enforce uniqueness
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
