# Generated by Django 5.0.14 on 2026-04-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_created_at_job_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='اسم الحقل')),
                ('field_type', models.CharField(choices=[('text', 'نص قصير'), ('textarea', 'نص طويل'), ('select', 'قائمة اختيار'), ('checkbox', 'نعم / لا'), ('date', 'تاريخ'), ('number', 'رقم'), ('file_upload', 'ملف (PDF, DOC, DOCX)'), ('image_upload', 'صورة (JPG, PNG, GIF)')], default='text', max_length=30)),
                ('options', models.TextField(blank=True, help_text='للقائمة المنسدلة فقط: أدخل الخيارات مفصولة بفاصلة. مثال: خيار1,خيار2,خيار3')),
                ('is_required', models.BooleanField(default=False, verbose_name='إلزامي')),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='jobs.job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
