# Generated by Django 5.0.14 on 2026-04-04 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المرحلة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('color', models.CharField(default='#primary', max_length=20, verbose_name='اللون')),
            ],
            options={
                'verbose_name': 'مرحلة التوظيف',
                'verbose_name_plural': 'مراحل التوظيف',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='المصدر')),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.candidate', verbose_name='المرشح')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='الوظيفة')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='pipeline.pipelinestage', verbose_name='المرحلة الحالية')),
            ],
            options={
                'verbose_name': 'تطبيق وظيفة',
                'verbose_name_plural': 'تطبيقات الوظائف',
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
