# Generated by Django 5.0.14 on 2026-04-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobcustomfield'),
        ('pipeline', '0002_application_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='application_files/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to='pipeline.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='jobs.jobcustomfield')),
            ],
        ),
    ]
