# Generated by Django 5.0.14 on 2026-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create_job', 'Create Job'), ('create_candidate', 'Create Candidate'), ('shortlist', 'Shortlist'), ('shortlisted', 'Shortlisted'), ('removed_shortlist', 'Removed Shortlist'), ('comment', 'Comment'), ('rate', 'Rate'), ('accept', 'Accept'), ('reject', 'Reject'), ('move_stage', 'Move Stage'), ('link_candidate', 'Link Candidate'), ('team_add', 'Team Add'), ('team_update', 'Team Update'), ('team_remove', 'Team Remove')], max_length=50),
        ),
    ]
